/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['[_nghost-%COMP%]{\r\n    //min-width: 1200px;\r\n    //padding: 55px 0 80px;\r\n    //background-color: #fff;\r\n    //font-size: 14px;\r\n    //display: block;\r\n    font-size: 12px;\r\n    background: #fafafa;\r\n    border-top: 1px solid #e6e6e6;\r\n    display: block;\r\n}\r\n\r\n.siteinfo[_ngcontent-%COMP%]{\r\n    padding: 100px 0 15px;\r\n    border-bottom: 1px solid #e6e6e6;\r\n    position: relative;\r\n    p{\r\n        margin-bottom: 5px;\r\n    }\r\n}\r\n\r\n.copyright[_ngcontent-%COMP%]{\r\n    color: #434d55;\r\n    font-size: 12px;\r\n    padding: 20px 0;\r\n    a{\r\n        color: #999;\r\n    }\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovd29yay94aWFvbGVpL3NyYy9hcHAvZm9vdGVyL2Zvb3Rlci5jb21wb25lbnQubGVzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi93b3JrL3hpYW9sZWkvc3JjL2FwcC9mb290ZXIvZm9vdGVyLmNvbXBvbmVudC5sZXNzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
