/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './about.component.less.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './about.component';
const styles_AboutComponent:any[] = [i0.styles];
export const RenderType_AboutComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_AboutComponent,data:{}});
export function View_AboutComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'div',[['class',
      'bj']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n\n'])),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),7,'div',[['class','container-box']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          4,'div',[['class','p-5']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['\n        '])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),1,'h3',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['领科，全球领先的物联网解决方案提供商，在物联网模块，esim，DCP连接管理平台，流量资费/运营有着十几年的行业经验和开发经验。'])),(_l()(),
          i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_AboutComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-about',([] as any[]),
      (null as any),(null as any),(null as any),View_AboutComponent_0,RenderType_AboutComponent)),
      i1.ɵdid(114688,(null as any),0,i2.AboutComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AboutComponentNgFactory:i1.ComponentFactory<i2.AboutComponent> = i1.ɵccf('app-about',
    i2.AboutComponent,View_AboutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovd29yay94aWFvbGVpL3NyYy9hcHAvYWJvdXQvYWJvdXQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L3dvcmsveGlhb2xlaS9zcmMvYXBwL2Fib3V0L2Fib3V0LmNvbXBvbmVudC50cyIsIm5nOi8vL0Y6L3dvcmsveGlhb2xlaS9zcmMvYXBwL2Fib3V0L2Fib3V0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovd29yay94aWFvbGVpL3NyYy9hcHAvYWJvdXQvYWJvdXQuY29tcG9uZW50LnRzLkFib3V0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImJqXCI+XHJcblxyXG48L2Rpdj5cclxuPGRpdiBjbGFzcz1cImNvbnRhaW5lci1ib3hcIj5cclxuICAgIDxkaXYgY2xhc3M9XCJwLTVcIj5cclxuICAgICAgICA8aDM+6aKG56eR77yM5YWo55CD6aKG5YWI55qE54mp6IGU572R6Kej5Yaz5pa55qGI5o+Q5L6b5ZWG77yM5Zyo54mp6IGU572R5qih5Z2X77yMZXNpbe+8jERDUOi/nuaOpeeuoeeQhuW5s+WPsO+8jOa1gemHj+i1hOi0uS/ov5DokKXmnInnnYDljYHlh6DlubTnmoTooYzkuJrnu4/pqozlkozlvIDlj5Hnu4/pqozjgII8L2gzPlxyXG4gICAgPC9kaXY+XHJcbjwvZGl2PlxyXG4iLCI8YXBwLWFib3V0PjwvYXBwLWFib3V0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQWdCLHlDQUVWO01BQ047VUFBQTtNQUEyQiwyQ0FDdkI7VUFBQTtVQUFBLGdCQUFpQiwrQ0FDYjtVQUFBO1VBQUEsNENBQUk7VUFBQSx1RUFBcUU7aUJBQUEsNEJBQ3ZFO01BQ0o7OztvQkNQTjtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
