/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from './index/index.component.ngfactory';
import * as i4 from './product/product.component.ngfactory';
import * as i5 from './postage/postage.component.ngfactory';
import * as i6 from './application/application.component.ngfactory';
import * as i7 from './customer/customer.component.ngfactory';
import * as i8 from './about/about.component.ngfactory';
import * as i9 from './app.component.ngfactory';
import * as i10 from '@angular/common';
import * as i11 from '@angular/platform-browser';
import * as i12 from '@angular/animations/browser';
import * as i13 from '@angular/platform-browser/animations';
import * as i14 from '@angular/animations';
import * as i15 from '@angular/router';
import * as i16 from '@angular/http';
import * as i17 from '@ngx-translate/core/src/translate.loader';
import * as i18 from '@ngx-translate/core/src/translate.parser';
import * as i19 from '@ngx-translate/core/src/missing-translation-handler';
import * as i20 from '@ngx-translate/core/src/translate.store';
import * as i21 from '@ngx-translate/core/src/translate.service';
import * as i22 from './index/index.component';
import * as i23 from './product/product.component';
import * as i24 from './postage/postage.component';
import * as i25 from './application/application.component';
import * as i26 from './customer/customer.component';
import * as i27 from './about/about.component';
import * as i28 from './app-routing.module';
import * as i29 from '@ngx-translate/core/index';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.IndexComponentNgFactory,i4.ProductComponentNgFactory,i5.PostageComponentNgFactory,
              i6.ApplicationComponentNgFactory,i7.CustomerComponentNgFactory,i8.AboutComponentNgFactory,
              i9.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i10.NgLocalization,
              i10.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.IterableDiffers,
              i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),
          i0.ɵmpd(4608,i11.DomSanitizer,i11.ɵe,[i10.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,
              (null as any),[i11.DomSanitizer]),i0.ɵmpd(4608,i11.HAMMER_GESTURE_CONFIG,
              i11.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,i11.EVENT_MANAGER_PLUGINS,
              (p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i11.ɵDomEventsPlugin(p0_0),new i11.ɵKeyEventsPlugin(p1_0),
                    new i11.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i10.DOCUMENT,i10.DOCUMENT,i10.DOCUMENT,i11.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i11.EventManager,i11.EventManager,[i11.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i11.ɵDomSharedStylesHost,i11.ɵDomSharedStylesHost,
              [i10.DOCUMENT]),i0.ɵmpd(4608,i11.ɵDomRendererFactory2,i11.ɵDomRendererFactory2,
              [i11.EventManager,i11.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i12.AnimationDriver,
              i13.ɵc,([] as any[])),i0.ɵmpd(5120,i12.ɵAnimationStyleNormalizer,i13.ɵd,
              ([] as any[])),i0.ɵmpd(4608,i12.ɵAnimationEngine,i13.ɵb,[i12.AnimationDriver,
              i12.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i13.ɵe,
              [i11.ɵDomRendererFactory2,i12.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i11.ɵSharedStylesHost,(null as any),[i11.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i11.Meta,i11.Meta,
              [i10.DOCUMENT]),i0.ɵmpd(4608,i11.Title,i11.Title,[i10.DOCUMENT]),i0.ɵmpd(4608,
              i14.AnimationBuilder,i13.ɵBrowserAnimationBuilder,[i0.RendererFactory2]),
          i0.ɵmpd(5120,i15.ActivatedRoute,i15.ɵf,[i15.Router]),i0.ɵmpd(4608,i15.NoPreloading,
              i15.NoPreloading,([] as any[])),i0.ɵmpd(6144,i15.PreloadingStrategy,
              (null as any),[i15.NoPreloading]),i0.ɵmpd(135680,i15.RouterPreloader,
              i15.RouterPreloader,[i15.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i15.PreloadingStrategy]),i0.ɵmpd(4608,i15.PreloadAllModules,
              i15.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i15.ROUTER_INITIALIZER,
              i15.ɵi,[i15.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i15.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i16.BrowserXhr,i16.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i16.ResponseOptions,i16.BaseResponseOptions,([] as any[])),
          i0.ɵmpd(5120,i16.XSRFStrategy,i16.ɵb,([] as any[])),i0.ɵmpd(4608,i16.XHRBackend,
              i16.XHRBackend,[i16.BrowserXhr,i16.ResponseOptions,i16.XSRFStrategy]),
          i0.ɵmpd(4608,i16.RequestOptions,i16.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i16.Http,i16.ɵc,[i16.XHRBackend,i16.RequestOptions]),i0.ɵmpd(5120,i17.TranslateLoader,
              i1.createTranslateLoader,[i16.Http]),i0.ɵmpd(4608,i18.TranslateParser,
              i18.TranslateDefaultParser,([] as any[])),i0.ɵmpd(4608,i19.MissingTranslationHandler,
              i19.FakeMissingTranslationHandler,([] as any[])),i0.ɵmpd(4608,i20.TranslateStore,
              i20.TranslateStore,([] as any[])),i0.ɵmpd(4608,i21.TranslateService,
              i21.TranslateService,[i20.TranslateStore,i17.TranslateLoader,i18.TranslateParser,
                  i19.MissingTranslationHandler,i21.USE_DEFAULT_LANG,i21.USE_STORE]),
          i0.ɵmpd(512,i10.CommonModule,i10.CommonModule,([] as any[])),i0.ɵmpd(1024,
              i0.ErrorHandler,i11.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,() => {
            return [i15.ɵb()];
          },([] as any[])),i0.ɵmpd(512,i15.ɵg,i15.ɵg,[i0.Injector]),i0.ɵmpd(256,i0.APP_ID,
              'ang4-seo-xiaolei',([] as any[])),i0.ɵmpd(2048,i11.ɵTRANSITION_ID,(null as any),
              [i0.APP_ID]),i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any,
              p2_0:any,p2_1:any,p2_2:any) => {
            return [i11.ɵc(p0_0,p0_1),i15.ɵh(p1_0),i11.ɵf(p2_0,p2_1,p2_2)];
          },[[2,i11.NgProbeToken],[2,i0.NgProbeToken],i15.ɵg,i11.ɵTRANSITION_ID,i10.DOCUMENT,
              i0.Injector]),i0.ɵmpd(512,i0.ApplicationInitStatus,i0.ApplicationInitStatus,
              [[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,i0.ɵe,[i0.NgZone,i0.ɵConsole,
              i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,i0.ApplicationInitStatus]),
          i0.ɵmpd(2048,i0.ApplicationRef,(null as any),[i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,
              i0.ApplicationModule,[i0.ApplicationRef]),i0.ɵmpd(512,i11.BrowserModule,
              i11.BrowserModule,[[3,i11.BrowserModule]]),i0.ɵmpd(512,i13.BrowserAnimationsModule,
              i13.BrowserAnimationsModule,([] as any[])),i0.ɵmpd(1024,i15.ɵa,i15.ɵd,
              [[3,i15.Router]]),i0.ɵmpd(512,i15.UrlSerializer,i15.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i15.ChildrenOutletContexts,i15.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i15.ROUTER_CONFIGURATION,{useHash:true},([] as any[])),
          i0.ɵmpd(1024,i10.LocationStrategy,i15.ɵc,[i10.PlatformLocation,[2,i10.APP_BASE_HREF],
              i15.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i10.Location,i10.Location,[i10.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i15.ROUTES,() => {
            return [[{path:'index',component:i22.IndexComponent},{path:'product',component:i23.ProductComponent},
                {path:'postage',component:i24.PostageComponent},{path:'application',
                    component:i25.ApplicationComponent},{path:'customer',component:i26.CustomerComponent},
                {path:'about',component:i27.AboutComponent},{path:'',redirectTo:'/index',
                    pathMatch:'full'},{path:'**',redirectTo:'/index',pathMatch:'full'}]];
          },([] as any[])),i0.ɵmpd(1024,i15.Router,i15.ɵe,[i0.ApplicationRef,i15.UrlSerializer,
              i15.ChildrenOutletContexts,i10.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i15.ROUTES,i15.ROUTER_CONFIGURATION,[2,i15.UrlHandlingStrategy],
              [2,i15.RouteReuseStrategy]]),i0.ɵmpd(512,i15.RouterModule,i15.RouterModule,
              [[2,i15.ɵa],[2,i15.Router]]),i0.ɵmpd(512,i28.AppRoutingModule,i28.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i16.HttpModule,i16.HttpModule,([] as any[])),
          i0.ɵmpd(512,i29.TranslateModule,i29.TranslateModule,([] as any[])),i0.ɵmpd(512,
              i1.AppModule,i1.AppModule,([] as any[])),i0.ɵmpd(256,i21.USE_STORE,(undefined as any),
              ([] as any[])),i0.ɵmpd(256,i21.USE_DEFAULT_LANG,(undefined as any),([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovd29yay94aWFvbGVpL3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi93b3JrL3hpYW9sZWkvc3JjL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
