/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.less.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './header/header.component.ngfactory';
import * as i3 from './header/header.component';
import * as i4 from '@ngx-translate/core/src/translate.service';
import * as i5 from '@angular/router';
import * as i6 from './footer/footer.component.ngfactory';
import * as i7 from './footer/footer.component';
import * as i8 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-header',([] as any[]),
      (null as any),(null as any),(null as any),i2.View_HeaderComponent_0,i2.RenderType_HeaderComponent)),
      i1.ɵdid(114688,(null as any),0,i3.HeaderComponent,[i4.TranslateService],(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),1,'div',[['class','main-top']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n\n'])),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),
          (null as any),4,'div',[['id','main']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i1.ɵdid(212992,(null as any),0,i5.RouterOutlet,[i5.ChildrenOutletContexts,i1.ViewContainerRef,
          i1.ComponentFactoryResolver,[8,(null as any)],i1.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),
          ['\n\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-footer',
          ([] as any[]),(null as any),(null as any),(null as any),i6.View_FooterComponent_0,
          i6.RenderType_FooterComponent)),i1.ɵdid(114688,(null as any),0,i7.FooterComponent,
          ([] as any[]),(null as any),(null as any)),(_l()(),i1.ɵted((null as any),
          ['\n\n'])),(_l()(),i1.ɵted((null as any),['\n\n'])),(_l()(),i1.ɵted((null as any),
          ['\n\n'])),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,1,0);
    _ck(_v,9,0);
    _ck(_v,13,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(49152,(null as any),0,i8.AppComponent,[i4.TranslateService],(null as any),
          (null as any))],(null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i8.AppComponent> = i1.ɵccf('app-root',
    i8.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovd29yay94aWFvbGVpL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi93b3JrL3hpYW9sZWkvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vRjovd29yay94aWFvbGVpL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovd29yay94aWFvbGVpL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8YXBwLWhlYWRlcj48L2FwcC1oZWFkZXI+XHJcbjxkaXYgY2xhc3M9XCJtYWluLXRvcFwiPlxyXG5cclxuPC9kaXY+XHJcbjxkaXYgaWQ9XCJtYWluXCI+XHJcbiAgICA8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XHJcbjwvZGl2PlxyXG5cclxuPGFwcC1mb290ZXI+PC9hcHAtZm9vdGVyPlxyXG5cclxuPCEtLTxkaXY+e3sgJ0hFTExPJyB8IHRyYW5zbGF0ZSB9fTwvZGl2Pi0tPlxyXG5cclxuPCEtLTxpbWcgW3NyY109XCInSU1HJyB8IHRyYW5zbGF0ZVwiPi0tPlxyXG5cclxuPCEtLTxidXR0b24gKGNsaWNrKT1cImNoYW5nZSgpXCI+5YiH5o2i6K+t6KiAPC9idXR0b24+LS0+XHJcbiIsIjxhcHAtcm9vdD48L2FwcC1yb290PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO2FBQUE7VUFBQSxlQUF5Qix1Q0FDekI7VUFBQTtVQUFBLDBEQUFzQjtVQUFBLFdBRWhCLHVDQUNOO1VBQUE7VUFBQSw4QkFBZTtNQUNYO1VBQUE7YUFBQTtzQ0FBQTtVQUFBLGVBQStCLHVDQUM3QjtVQUFBLFdBRU47VUFBQTt1Q0FBQSxVQUFBO1VBQUEsMkNBQXlCO1VBQUEsV0FFa0IseUNBRUw7VUFBQSxXQUVTO0lBZC9DO0lBS0k7SUFHSjs7OztvQkNSQTtNQUFBO2FBQUE7VUFBQTs7OyJ9
