/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.main-top[_ngcontent-%COMP%]{\r\n    height: 70px;\r\n    width: 100%;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovd29yay94aWFvbGVpL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5sZXNzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L3dvcmsveGlhb2xlaS9zcmMvYXBwL2FwcC5jb21wb25lbnQubGVzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
