/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './index.component.less.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../slide-img/slide-img.component.ngfactory';
import * as i3 from '../slide-img/slide-img.component';
import * as i4 from './index.component';
const styles_IndexComponent:any[] = [i0.styles];
export const RenderType_IndexComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_IndexComponent,data:{}});
export function View_IndexComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[i1.ɵqud(402653184,1,{slideImgRef:0}),(_l()(),i1.ɵted((null as any),
      ['\n\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class','container-box']],
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
      1,'app-slide-img',([] as any[]),(null as any),(null as any),(null as any),i2.View_SlideImgComponent_0,
      i2.RenderType_SlideImgComponent)),i1.ɵdid(638976,[[1,4],['slideImg',4]],0,i3.SlideImgComponent,
      [i1.Renderer2],{list:[0,'list'],width:[1,'width'],height:[2,'height']},(null as any)),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),['\n']))],
      (_ck,_v) => {
        var _co:i4.IndexComponent = _v.component;
        const currVal_0:any = _co.list;
        const currVal_1:any = 2000;
        const currVal_2:any = 690;
        _ck(_v,5,0,currVal_0,currVal_1,currVal_2);
      },(null as any));
}
export function View_IndexComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-index',([] as any[]),
      (null as any),(null as any),(null as any),View_IndexComponent_0,RenderType_IndexComponent)),
      i1.ɵdid(114688,(null as any),0,i4.IndexComponent,([] as any[]),(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const IndexComponentNgFactory:i1.ComponentFactory<i4.IndexComponent> = i1.ɵccf('app-index',
    i4.IndexComponent,View_IndexComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovd29yay94aWFvbGVpL3NyYy9hcHAvaW5kZXgvaW5kZXguY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L3dvcmsveGlhb2xlaS9zcmMvYXBwL2luZGV4L2luZGV4LmNvbXBvbmVudC50cyIsIm5nOi8vL0Y6L3dvcmsveGlhb2xlaS9zcmMvYXBwL2luZGV4L2luZGV4LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovd29yay94aWFvbGVpL3NyYy9hcHAvaW5kZXgvaW5kZXguY29tcG9uZW50LnRzLkluZGV4Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPCEtLTxkaXYgY2xhc3M9XCJjb250YWluZXItYm94XCI+XHJcbiAgICA8ZGl2IGNsYXNzPVwiYmFubmVyLXNsaWRlXCI+XHJcblxyXG4gICAgPC9kaXY+XHJcbjwvZGl2Pi0tPlxyXG5cclxuPGRpdiBjbGFzcz1cImNvbnRhaW5lci1ib3hcIj5cclxuICAgIDxhcHAtc2xpZGUtaW1nIFtsaXN0XT1cImxpc3RcIiBbd2lkdGhdPVwiMjAwMFwiIFtoZWlnaHRdPVwiNjkwXCIgI3NsaWRlSW1nPVwic2xpZGVJbWdcIj48L2FwcC1zbGlkZS1pbWc+XHJcbjwvZGl2PlxyXG4iLCI8YXBwLWluZGV4PjwvYXBwLWluZGV4PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O3lEQ0lTO01BQUEsV0FFVDtNQUFBLHdFQUEyQjthQUFBLDRCQUN2QjtNQUFBO3FDQUFBLFVBQUE7TUFBQTtNQUFnRyx1Q0FDOUY7OztRQURhO1FBQWM7UUFBZTtRQUE1QyxXQUFlLFVBQWMsVUFBZSxTQUE1Qzs7OztvQkNQSjtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
